# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpparma_hello_world
#'
rcpparma_hello_world <- function() {
    .Call(`_LRDistReg_rcpparma_hello_world`)
}

#' rcpparma_outerproduct
#' @param x A vector
#'
rcpparma_outerproduct <- function(x) {
    .Call(`_LRDistReg_rcpparma_outerproduct`, x)
}

#' rcpparma_innerproduct
#' @param x A vector
#'
rcpparma_innerproduct <- function(x) {
    .Call(`_LRDistReg_rcpparma_innerproduct`, x)
}

#' rcpparma_bothproducts
#' @param x A vector
#'
rcpparma_bothproducts <- function(x) {
    .Call(`_LRDistReg_rcpparma_bothproducts`, x)
}

