# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' v-tilde and gamma-tilde functions (row), C++ version
#'
#' @param theta Log-parameter
#' @param ell Number of unique covariates
#' @param m Number of unique responses
#' @param n Sample size
#' @param mM (m_j,M_j) index pairs
#' @param w_ul Cumulative row-sums of sample weights
#'
#' @return v-tilde and gamma-tilde functions
#'
#' @export
vgamma_tilde1_cpp <- function(theta, ell, m, n, mM, w_ul) {
    .Call(`_LRDistReg_vgamma_tilde1_cpp`, theta, ell, m, n, mM, w_ul)
}

#' v-tilde and gamma-tilde functions (column), C++ version
#'
#' @param theta Log-parameter
#' @param ell Number of unique covariates
#' @param m Number of unique responses
#' @param n Sample size
#' @param lL (l_k,L_k) index pairs
#' @param w_ol Cumulative column-sums of sample weights
#'
#' @return v-tilde and gamma-tilde functions
#'
#' @export
vgamma_tilde2_cpp <- function(theta, ell, m, n, lL, w_ol) {
    .Call(`_LRDistReg_vgamma_tilde2_cpp`, theta, ell, m, n, lL, w_ol)
}

#' Negative log-likelihood in terms of log-parameter, C++ version
#'
#' @param theta Log-parameter
#' @param ell Number of unique covariates
#' @param n Sample size
#' @param mM (m_j,M_j) index pairs
#' @param w Sample weights
#'
#' @return Negative log-likelihood in terms of log-parameter
#'
#' @export
f_theta_cpp <- function(theta, ell, n, mM, w) {
    .Call(`_LRDistReg_f_theta_cpp`, theta, ell, n, mM, w)
}

#' Prepare the data, C++ version
#'
#' @param X Covariates
#' @param Y Responses
#' @param W User-specified weights
#'
#' @return A list of pre-computed parameters necessary for the estimation
#'
#' @export
prepare_data_cpp <- function(X, Y, W) {
    .Call(`_LRDistReg_prepare_data_cpp`, X, Y, W)
}

#' Transforms lambda (row) into theta, C++ version
#'
#' @param lambda Row-wise differences
#' @param ell Number of unique covariates
#' @param m Number of unique responses
#' @param mM (m_j,M_j) index pairs
#'
#' @return Transformed parameter
#'
#' @export
lambda1_to_theta_cpp <- function(lambda, ell, m, mM) {
    .Call(`_LRDistReg_lambda1_to_theta_cpp`, lambda, ell, m, mM)
}

#' Transforms lambda (column) into theta, C++ version
#'
#' @param lambda Column-wise differences
#' @param ell Number of unique covariates
#' @param m Number of unique responses
#' @param lL (l_k,L_k) index pairs
#'
#' @return Transformed parameter
#'
#' @export
lambda2_to_theta_cpp <- function(lambda, ell, m, lL) {
    .Call(`_LRDistReg_lambda2_to_theta_cpp`, lambda, ell, m, lL)
}

